import sgs

print("TESTING CALCULATE MODULE STRUCTURE")
sgs.calculate.allocation()
sgs.calculate.coobs()
sgs.calculate.distance()
sgs.calculate.lhs_optimal()
sgs.calculate.pop()
sgs.calculate.principal_components()
sgs.calculate.representation()
sgs.calculate.sample_size()
print()

print("TESTING SAMPLE MODULE STRUCTURE")
sgs.sample.ahels()
sgs.sample.balanced()
sgs.sample.clhs()
sgs.sample.existing()
sgs.sample.nc()
sgs.sample.srs()
sgs.sample.strat()
sgs.sample.sys_strat()
sgs.sample.systematic()
print()

print("TESTING STRATIFY MODULE STRUCTURE")
sgs.stratify.breaks()
sgs.stratify.kmeans()
sgs.stratify.poly()
sgs.stratify.quantiles()
sgs.stratify.map()
print()

#sgs.utils.useful_function()
