var searchData=
[
  ['a_20quick_20pip_20install_20sgs_20for_20now_20the_20package_20can_20be_20installed_20and_20built_20as_20follows_20depending_20on_20operating_20system_0',['NOTE: when distributed, the package will be available through PyPI and thus a quick &apos;pip install sgs&apos;. For now, the package can be installed and built as follows depending on operating system.',['../index.html#autotoc_md4',1,'']]],
  ['accessing_20raster_20data_1',['Accessing raster data',['../classsgs_1_1utils_1_1raster_1_1SpatialRaster.html#autotoc_md41',1,'']]],
  ['accessing_20raster_20information_2',['Accessing raster information',['../classsgs_1_1utils_1_1raster_1_1SpatialRaster.html#autotoc_md42',1,'']]],
  ['and_20built_20as_20follows_20depending_20on_20operating_20system_3',['NOTE: when distributed, the package will be available through PyPI and thus a quick &apos;pip install sgs&apos;. For now, the package can be installed and built as follows depending on operating system.',['../index.html#autotoc_md4',1,'']]],
  ['and_20thus_20a_20quick_20pip_20install_20sgs_20for_20now_20the_20package_20can_20be_20installed_20and_20built_20as_20follows_20depending_20on_20operating_20system_4',['NOTE: when distributed, the package will be available through PyPI and thus a quick &apos;pip install sgs&apos;. For now, the package can be installed and built as follows depending on operating system.',['../index.html#autotoc_md4',1,'']]],
  ['as_20follows_20depending_20on_20operating_20system_5',['NOTE: when distributed, the package will be available through PyPI and thus a quick &apos;pip install sgs&apos;. For now, the package can be installed and built as follows depending on operating system.',['../index.html#autotoc_md4',1,'']]],
  ['attributes_6',['Public Attributes',['../classsgs_1_1utils_1_1raster_1_1SpatialRaster.html#autotoc_md44',1,'']]],
  ['attributes_3a_7',['Public Attributes:',['../classsgs_1_1utils_1_1vector_1_1SpatialVector.html#autotoc_md46',1,'']]],
  ['available_20through_20pypi_20and_20thus_20a_20quick_20pip_20install_20sgs_20for_20now_20the_20package_20can_20be_20installed_20and_20built_20as_20follows_20depending_20on_20operating_20system_8',['NOTE: when distributed, the package will be available through PyPI and thus a quick &apos;pip install sgs&apos;. For now, the package can be installed and built as follows depending on operating system.',['../index.html#autotoc_md4',1,'']]]
];
