on:
  push:
    branches:
      - fix_upgraded_dep_build
permissions:
  contents:
    write

jobs:
  test-linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.12" ]
        
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      
      - name: Checkout repository and submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
        
      - name: Install and build C++ dependencies
        run: bash scripts/install.sh
        
      - name: Build package
        run: export PKG_CONFIG_PATH="${PWD}/sgspy/extern/vcpkg/installed/x64-linux/lib/pkgconfig" |
            echo "$PKG_CONFIG_PATH" |
            pip install .
        
